-- GEUSTBOOK_USER 테이블 생성
CREATE TABLE GEUSTBOOK_USER(
  EMAIL VARCHAR2(30) PRIMARY KEY, 
  NAME VARCHAR2(30) NOT NULL, 
  PASSWORD VARCHAR2(30) NOT NULL
);

-- GUESTBOOK 테이블 생성
CREATE TABLE GUESTBOOK (  
  EMAIL VARCHAR2(30) NOT NULL, 
  NAME VARCHAR2(30) NOT NULL,
  NO NUMBER PRIMARY KEY, 
  DATES DATE NOT NULL, 
  CONTENT VARCHAR2(100) NOT NULL,
  CONSTRAINT fk_email foreign key(email) references GEUSTBOOK_USER (email) on delete cascade
);

-- GUESTBOOK_SEQ 시퀀스 생성
CREATE SEQUENCE GUESTBOOK_SEQ;